### ISSUE TITLE
https://github.com/MattCollins-Jones/PowerAutomateArtemisFramework/wiki/Cloud-Flow-Coding-Standards#expressions

### ISSUE THREAD

**Issue by ToddShelton** [MattCollins-Jones/PowerAutomateArtemisFramework#1]
Typo fix: "When using this, it is possible to ident your code for easier reading. " "ident" should be "indent".

**Comment by ToddShelton** [comment]
Also at https://github.com/MattCollins-Jones/PowerAutomateArtemisFramework/wiki/Cloud-Flow-Coding-Standards#connectionsservice-accountsservice-principles, "Service Principles" should be "Service Principals".

**Comment by ToddShelton** [comment]
This is a beautiful piece of work.  Thanks, Matt.

**Comment by MattCollins-Jones** [comment]
Awesome, thank you for catching these. I've updated it now. Thank you for the kinds words 😊
