### ISSUE TITLE
Minor typo succulent --> succinct

### ISSUE THREAD

**Issue by AlexMcLachlan** [MattCollins-Jones/PowerAutomateArtemisFramework#2]
Should 'succulent' be 'succinct' in "The Description field does have a limited number of characters, so if you reach this limit, considered updating previous entries to be more succulent or moving your version history to a Compose Step inside the flow itself"? Although I do like the idea of succulent descriptions :)

**Comment by MattCollins-Jones** [comment]
Tiny plant descriptions, I think, are the future. 😅 Thanks for spotting @AlexMcLachlan!
