### ISSUE TITLE
User Story reference in the Flow Description

### ISSUE THREAD

**Issue by AlexMcLachlan** [MattCollins-Jones/PowerAutomateArtemisFramework#3]
Hi Matt, great work! 

I put the user story reference in the description, such as #12345 as this provides a link back to the reason for adding it. Would this, or something similar, be worth adding?

As a note: one reason I use this is that I have a flow that creates markdown files for all the customer process descriptions, so the use of '#' then translates into the user story title in the Azure DevOps Wiki page.

Best wishes, Alex

**Comment by MattCollins-Jones** [comment]
Hey @AlexMcLachlan 

Yes, that's a great idea, especially if space is a premium in the description, using this to link to tickets/backlog items where they can contain more details, would be valuable. I'll update the guide.

thanks
Matt

**Comment by MattCollins-Jones** [comment]
Updated the flow creation part of the guide to reference this idea. Thanks again @AlexMcLachlan 👍
